kind: Service
apiVersion: v1
metadata:
  name: test-app
spec:
  selector:
    app: test-app
  ports:
    - port: 8080
  type: NodePort
---
kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: test-app
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: test-app
    spec:
      containers:
      - name: test-app
        image: georgy/test-app:2
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /app/resources/time
            port: 8080
        readinessProbe:
          httpGet:
            path: /app/resources/time
            port: 8080
      restartPolicy: Always